name: towchat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  socket_io: ^1.0.1
  flutter_chat_ui: ^1.6.6
  get: 4.6.5
  flutter: 
    sdk: flutter
  uuid: ^3.0.6
  path_provider: ^2.0.11
  open_filex: ^4.2.2
  mime: ^1.0.2
  intl: ^0.17.0
  image_picker: ^0.8.6
  http: ^0.13.5
  flutter_chat_types: ^3.6.0
  file_picker: ^5.2.2

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
   - assets/